### ISSUE TITLE
Create tutorial for experimental feature of `notation policy import/show` command

### ISSUE THREAD

**Issue by yizha1** [notaryproject/notaryproject.dev#167]
`notation policy import/show` is the new experimental feature for RC-4. A tutorial guide is needed for users to understand usage of this feature. This guide will be placed under https://github.com/notaryproject/notaryproject.dev/tree/main/content/en/docs/tutorials

**Comment by zr-msft** [comment]
@yizha1  can you provide details on:
- why would a user use this?
- what does `import` do?
- is there an export feature? how to i create a policy to share with someone else?
- Are there any limitations/edge cases (what happens if the policy that you're trying to import has the same name as an existing policy)?
- Do you want this to be a full tutorial? or a guide that explains the feature? A tutorial needs to have a full end-to-end scenario and takes more time to develop.

Labeling this as blocked until RC-4 ships.

**Comment by yizha1** [comment]
@zr-msft  Thanks for the comments.

We have a phased plan to introduce CLI commands for managing trust policy configuration, so that users don't need to:

1. Know the name of trust policy file, `trustpolicy.json`
2. Know what is the configuration directory that trust policy file need to be stored
3. figure out how to view trust policy configuration
4. Manual edit trust policy file to update properties

In the upcoming RC-4, we introduced `notation policy import` and `notation policy show` to address the first three issues, so that users can 
- Import trust policy configuration from a JSON file (any file name is allowed), if there is trust policy configuration, user can choose whether to override or not.
- Show trust policy configuration and re-direct it into a JSON file

A guide explains how to use `notation policy import` and `notation policy show` commands.  I am thinking we can do similar thing as helm, see example https://helm.sh/docs/helm/helm_install/

After 1.0 release, we plan to introduce more commands like `notation policy add` to add a policy or `notation policy delete` to delete a policy.

Any comments are welcome.
