### ISSUE TITLE
Create the blog post for the security audit report announcement

### ISSUE THREAD

**Issue by FeynmanZhou** [notaryproject/notaryproject.dev#298]
We started the security audit review with Ada Logics in Feb 2023 according to https://github.com/notaryproject/notaryproject/issues/239, Ada Logics recently finalized the security audit to multiple Notation repositories. The next step is to write a blog post from the Notary Project's perspective and publish it on the Notary website.

**Comment by 1Shubham7** [comment]
@FeynmanZhou I am not very expert in technologies used here, but am ready to research and give time. I know decent golang, hugo etc and I have been writing tech blogs since 3-4 months . If its possible for a newbie to research and write a blog post, Please do assign me the issue, I have been trying to contribute to the project since long and am ready to research and learn on the go.

**Comment by FeynmanZhou** [comment]
@1Shubham7 Thanks for your interest! This issue is open for Notary Project maintainers who participated in the Notary security audit with the 3p audit team. 

I can find another good-first issue for you to have a try.

**Comment by 1Shubham7** [comment]
Ok @FeynmanZhou.
