### ISSUE TITLE
Update site with versioned release information

### ISSUE THREAD

**Issue by zr-msft** [notaryproject/notaryproject.dev#350]
Related to #341 

Docs site needs to show versioned content starting with release 1.1.0. 

High-level tasks:
- Branching strategy
- "System Release" doc that shows versions of subprojects for a Notary Project release
- How versioned content is accessed (e.g. urls, redirects, UI elements, etc)
- Removing unsupported content
- Localization strategy

We can record decisions and discussions in this issue and link out to any PRs/Issues implementing those decisions.

**Comment by FeynmanZhou** [comment]
We still need to support version control on the documentation site.

**Comment by FeynmanZhou** [comment]
Reference: https://www.docsy.dev/docs/adding-content/versioning/

**Comment by FeynmanZhou** [comment]
A versioned website URL ensures the link will not be changed or broken in the future. Inspired by [KubeFlow website versioning strategy](https://github.com/kubeflow/website#versioning-of-the-docs), I want to propose the version control strategy as follows. 

The versioned website follows this convention:

1. The website version aligns with the Notation CLI version, because most of the website content are related to CLI and Notary Project is generic brand that doesn't have a versioning strategy

2. Use different branch and sub-domains to support version control:

-   notaryproject.dev always points to the current **main** branch, means the dev branch for next release
-   `vX-Y.notaryproject.dev` points to the stable release, for example, https://v1-1.notaryproject.dev/ points to v1.1 website

**Comment by toddysm** [comment]
@whalelines idea to have `https://notaryproject.dev/docs/PRODUCT/VERSION/` is very good and I remember we discussed this in a few meetings last summer. The problem we hit was with fexibility of the hosting and whether this structure will be possible and whether we can do it from the mono-repo for the site right now. It will be much better experience if we have this one, of course.

At a min, we should link to the place where other docs can be found on the docs home page. As a compromise, we may want to go with the current proposal for this version of the CLI and rethink the whole docs structure for the next.
